version: 2.1

executors:
  dotnetcore:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
  ghr:
    docker:
      - image: cibuilds/github:0.12.1

jobs:
  build-for-macos:
    executor: dotnetcore
    steps:
      - checkout
      - run:
          name: Build osx executable
          command: dotnet publish ./Anrepack.Cli --configuration=Release --runtime=osx-x64 --version-suffix=osx-SNAPSHOT-${CIRCLE_SHA1} --self-contained=false --output=/tmp/app-published/osx
      - persist_to_workspace:
          root: /tmp/app-published
          paths:
            - osx/
  build-for-macos-selfcontained:
    executor: dotnetcore
    steps:
      - checkout
      - run:
          name: Build osx executable
          command: dotnet publish ./Anrepack.Cli --configuration=Release --runtime=osx-x64 --version-suffix=osx-selfcontained-SNAPSHOT-${CIRCLE_SHA1} --self-contained=true --output=/tmp/app-published/osx-selfcontained
      - persist_to_workspace:
          root: /tmp/app-published
          paths:
            - osx-selfcontained/
  build-for-windows:
    executor: dotnetcore
    steps:
      - checkout
      - run:
          name: Build windows executable
          command: dotnet publish ./Anrepack.Cli --configuration=Release --runtime=win-x64 --version-suffix=windows-SNAPSHOT-${CIRCLE_SHA1} --self-contained=false --output=/tmp/app-published/windows
      - persist_to_workspace:
          root: /tmp/app-published
          paths:
            - windows/
  build-for-windows-selfcontained:
    executor: dotnetcore
    steps:
      - checkout
      - run:
          name: Build windows executable
          command: dotnet publish ./Anrepack.Cli --configuration=Release --runtime=win-x64 --version-suffix=windows-selfcontained-SNAPSHOT-${CIRCLE_SHA1} --self-contained=true --output=/tmp/app-published/windows-selfcontained
      - persist_to_workspace:
          root: /tmp/app-published
          paths:
            - windows-selfcontained/
  deploy:
    executor: ghr
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/app-published
      - run:
          name: "List"
          command: ls -la /tmp/app-published
      - run:
          name: Create output dir
          command: mkdir -p /tmp/app-archived
      - run:
          name: Archive for osx
          command: zip /tmp/app-archived/osx.zip -r /tmp/app-published/osx
      - run:
          name: Archive for osx-selfcontained
          command: zip /tmp/app-archived/osx-selfcontained.zip -r /tmp/app-published/osx-selfcontained
      - run:
          name: Archive for windows
          command: zip /tmp/app-archived/windows.zip -r /tmp/app-published/windows
      - run:
          name: Archive for windows-selfcontained
          command: zip /tmp/app-archived/windows-selfcontained.zip -r /tmp/app-published/windows-selfcontained
      - store_artifacts:
          path: /tmp/app-archived

workflows:
  build-and-publish:
    jobs:
      - build-for-macos
      - build-for-windows
      - build-for-macos-selfcontained
      - build-for-windows-selfcontained
      - deploy:
          requires:
            - build-for-macos
            - build-for-windows
            - build-for-macos-selfcontained
            - build-for-windows-selfcontained
